### PR TITLE
migration to react 16

### PR DESCRIPTION
**Pull request by henryroach**
Project updated to react v16. I've tested these changes in our project and it seems to be fine but I'm not an JS expert so feel free to comment :-)

### CODE REVIEW

**Comment by StephenChou1017** [comment]
@henryroach 
Hi，I'm glad that you sent this PR:-), so I first merged your code into my repo and compiled, I found many compile errors as following:

 Can't resolve 'react/lib/ReactMount' in 'C:\Stephen\Demospace\react-big-scheduler-master\example'
Can't resolve 'react/lib/React' in 'C:\Stephen\Demospace\react-big-scheduler-master\node_modules\react-dom\lib'
Can't resolve 'react/lib/ReactCurrentOwner' in 'C:\Stephen\Demospace\react-big-scheduler-master\node_modules\react-dom\lib'
Can't resolve 'react/lib/ReactComponentTreeHook' in 'C:\Stephen\Demospace\react-big-scheduler-master\node_modules\react-dom\lib'
Can't resolve 'react/lib/getNextDebugID' in 'C:\Stephen\Demospace\react-big-scheduler-master\node_modules\react-dom\lib'

then I downloaded your repo directly, "npm install", "npm run example", the errors above still existed.
did I miss anything?:-)

**Comment by henryroach** [comment]
Hello, no you didn't miss anything but I did :-) I'm currently working to resolve these errors in next commit.

**Comment by henryroach** [comment]
Great, thanks! May I ask you when will be new version in npm?

**Comment by StephenChou1017** [comment]
I'll publish one as soon as possible after fixing the styling errors.

**Comment by StephenChou1017** [comment]
@henryroach I published one version in npm today :-)

**Comment by henryroach** [comment]
Yeah, I've used it already :-) thanks!

**Pull request merged**
