### PR TITLE
Option to don't show nonWorkingTime

### PR DESCRIPTION
**Pull request by ZomerVinicius**
Like the image below:
screenshot from 2018-11-26 16-48-25
It's necessary to set flag **showNonWorkingTime** on **config.js** to **false**

### CODE REVIEW

**Comment by StephenChou1017** [comment]
@ZomerVinicius 
Hi, I see you commit 2 PRs which are both about nonWorkingTime, thanks for that:-). I comment them all here now.

I think the schedulerData.behaviors.isNonWorkingTimeFunc gives you the most flexibility to define when is the non-working time.

If you want to set startHour  and endHour, you can do as below:
`
//customize isNonWorkingTimeFunc first
myIsNonWorkingTime = (schedulerData, time) => {
    const { localeMoment, config } = schedulerData;
    if(schedulerData.cellUnit === CellUnits.Hour){
        let hour = localeMoment(time).hour();
        if(hour < config.startHour || hour > endHour)
            return true;
    }

    return false;
}
//initialize the schedulerData object
let schedulerData = new SchedulerData(new moment().format(DATE_FORMAT), ViewTypes.Week, false, false, {
    startHour: 6,
    endHour: 20
}, {
    isNonWorkingTimeFunc: myIsNonWorkingTime
});
`

If you don't want to set non-working time, you can do as below:
`
//customize isNonWorkingTimeFunc first, just return false for all
myIsNonWorkingTime = (schedulerData, time) => {
    return false;
}
//initialize the schedulerData object
let schedulerData = new SchedulerData(new moment().format(DATE_FORMAT), ViewTypes.Week, false, false, undefined, {
    isNonWorkingTimeFunc: myIsNonWorkingTime
});
`

**Comment by ZomerVinicius** [comment]
Hi @StephenChou1017 , thanks for your reply, 

About the start and end hour, your solution is better!

But talking about don't showing the non-working time,

I think you didn't understand what I was trying to show,

In the image that is on this PR, I set the working hours and hide them on the scheduler,

I can't do it with the code you shared,

Do you have a better solution for this?

**Comment by StephenChou1017** [comment]
If you just want to display working hours in day view, you may try to set schedulerData.config.dayStartFrom(defaults 0) and schedulerData.config.dayStopTo(defaults 23). i.e. we start work at 9:00am and get off work at 6:00pm, we can set schedulerData.config.dayStartFrom to 9 and set schedulerData.config.dayStopTo to 18.

**Comment by ZomerVinicius** [comment]
I did what you suggested, 

It works when the period is not custom,

But when it is, this config set the day start to the hour I set,

And the day stop only to the last day of the period selected,

Not each day of the period,

Like the images below, that shows when I set dayStartFrom to 8 and dayStop to 18:

screenshot from 2018-11-28 16-50-21
screenshot from 2018-11-28 16-50-34
screenshot from 2018-11-28 16-50-26

Should I open an issue for it?

**Comment by StephenChou1017** [comment]
Yes, It's an issue in custom period, I'll take a look:-)

**Pull request closed without merging**
