### PR TITLE
Table headers customizing, option to disable calendar popup

### PR DESCRIPTION
**Pull request by DadUndead**
I've added some useful configuration options to customize table headers and to disable calendar popup.  See updated README.md

### CODE REVIEW

**Comment by StephenChou1017** [comment]
@DadUndead 
Hi, glad to receive your PR, thank you, below is my feedback:-):

1. Add calendarPopoverEnabled option is a good design, it's OK.

2. It seems that you forgot to commit the css class 'current-date'  to your repo:-)

3. I have the plan to customize the table headers style, just like what you are doing in your PR. But we'd better merge nonAgendaDayCellHeaderRenderer and nonAgendaOtherCellHeaderRenderer into nonAgendaCellHeaderRenderer(schedulerData, headerItem, width),  and put it in Scheduler.propTypes, just like Scheduler.propTypes.eventItemTemplateResolver and Scheduler.propTypes.slotItemTemplateResolver do. Because we may need the view context(props, state or other react Jsxes) when we customize the cell header styles, and we can get current view type(Day or other) and configs, behaviors from the passed schedulerData object directly.

Hope you can adjust and send PR again:-)

**Comment by DadUndead** [comment]
@StephenChou1017 
Hi, thanks for review!
I didn't commit css class 'current-date' on purpose to enable it in css but to save default styles 'as is'. At first I wanted to add config options like currentTimeHeadColor and currentTimeHeadBgColor but css class is more flexible so I settled on this. If you have your opinion, let's discuss ;)
I agree about renderers, hope to update my PR soon.

**Comment by DadUndead** [comment]
@StephenChou1017
I've added changes we discussed above.
I also figured out that it's easy enough to add custom header template resolver to determine if header cell displays current date. So I removed 'current-date' class from the default template.

**Comment by StephenChou1017** [comment]
@DadUndead 
Great job, I'll update the online example later, thank you again:-)

**Pull request merged**
